// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview A flow to suggest meal adjustments based on food log analysis and user goals.
 *
 * - suggestMealAdjustment - A function that suggests adjustments to the user's next meal or activity level to help them stay on track with their diet.
 * - SuggestMealAdjustmentInput - The input type for the suggestMealAdjustment function.
 * - SuggestMealAdjustmentOutput - The return type for the suggestMealAdjustment function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const SuggestMealAdjustmentInputSchema = z.object({
  foodLog: z
    .string()
    .describe(
      'A detailed log of the user\u2019s recent food intake, including meal times, food items, and estimated quantities.'
    ),
  dietPlan: z
    .string()
    .describe(
      'The user\u2019s current diet plan, including daily caloric and macronutrient goals.'
    ),
  weightGoal: z
    .string()
    .describe(
      'The user\u2019s weight goal (e.g., lose 1 pound per week, maintain weight).'
    ),
  activityLevel: z
    .string()
    .describe(
      'The user\u2019s current activity level (e.g., sedentary, lightly active, moderately active, very active).'
    ),
});
export type SuggestMealAdjustmentInput = z.infer<
  typeof SuggestMealAdjustmentInputSchema
>;

const SuggestMealAdjustmentOutputSchema = z.object({
  adjustmentSuggestions: z
    .string()
    .describe(
      'Suggestions for adjusting the user\u2019s next meal or activity level to align with their diet plan and weight goal.'
    ),
});
export type SuggestMealAdjustmentOutput = z.infer<
  typeof SuggestMealAdjustmentOutputSchema
>;

export async function suggestMealAdjustment(
  input: SuggestMealAdjustmentInput
): Promise<SuggestMealAdjustmentOutput> {
  return suggestMealAdjustmentFlow(input);
}

const prompt = ai.definePrompt({
  name: 'suggestMealAdjustmentPrompt',
  input: {schema: SuggestMealAdjustmentInputSchema},
  output: {schema: SuggestMealAdjustmentOutputSchema},
  prompt: `You are a nutritionist providing personalized advice to help users stay on track with their diet and weight goals.

Analyze the user's food log in relation to their diet plan and weight goal. Consider their activity level when making recommendations.

Food Log: {{{foodLog}}}
Diet Plan: {{{dietPlan}}}
Weight Goal: {{{weightGoal}}}
Activity Level: {{{activityLevel}}}

Based on this information, provide specific and actionable suggestions for adjusting their next meal or activity level to better align with their goals.  Be concise.

Adjustment Suggestions:`,
});

const suggestMealAdjustmentFlow = ai.defineFlow(
  {
    name: 'suggestMealAdjustmentFlow',
    inputSchema: SuggestMealAdjustmentInputSchema,
    outputSchema: SuggestMealAdjustmentOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
